# I used Jekyll to build this website.                             
#  Teaching credits go to Amanda Visconti (https://doi.org/10.46430/phen0048).



title: Jayati Dev
email: devjayati at outlook dot com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devjayati.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dev_jayati
github_username:  devjayati

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
